### ISSUE TITLE
elasticsearch-search-source won't let me define basic authentication

### ISSUE THREAD

**Issue by MarcoMartins86** [apache/camel-kamelets#1056] opened 2022-09-29 11:33 UTC
While trying to set the basic authentication (user, password) I got the error `Unknown parameters=[{password=xxxxxx, user=xxxxxx}]` I think the bug is really on [Camel repository](https://github.com/apache/camel) but I can't open an issue there.

The reason I think it's a bug there is that the [documentation](https://camel.netlify.app/components/latest/elasticsearch-rest-component.html) says that `user` and `password` are options but when I try to define a route directly (without using the kamelet), `elasticsearch-rest://clusterName?password=xxxxxx&user=xxxxxx` gives me the same error.

I've tried to debug the problem and notice that on `ElasticsearchEndpointConfigurer.java` the `user` and `password` are not present on the switches cases, all other options are, but maybe this is on purpose since these are the only ones with `@Metadata(secret = true)` on `ElasticsearchComponent.java`.
Also, if `ElasticsearchEndpoint` class `@UriEndpoint` annotation had the flag `lenientProperties = true`, it would skip the validation where the error originates, but dunno if it would then configure the `user` and `password` options with the correct value.

Or maybe it's just me that is missing something and can't get this to work on [camel-quarkus](https://github.com/apache/camel-quarkus).

**Comment by oscerd** [comment] 2022-09-29 11:40
I don't think this is right project to ask: if it's related to camel-quarkus you should there in the issue tracker on Github. If it's a problem at Camel level you should open an issue at https://issues.apache.org/jira/browse/CAMEL

By the way it's not a bug. You need to set the user and password at component level. This mean you cannot append user and password to endpoint URI. Instead you should either define:

```
camel.component.elasticsearch-rest.user 
camel.component.elasticsearch-rest.password
```

in your application properties file. Or you should create a component and use it directly like this snippet:

https://camel.netlify.app/components/latest/elasticsearch-rest-component.html#_configure_the_component_and_enable_basic_authentication

This issue doesn't report the version you're using. By the way the solution should be what I wrote.

For sure this is not something related to Kamelets.

I'm going to close this.

**Comment by MarcoMartins86** [comment] 2022-09-29 14:27
Thank you for your replay, nevertheless, if `user` and `password` can't be a query parameter and are only set that way, should they be present as optional on the kamelet definition? Because as soon as they have a value, there will be a parse error (just tested with plain camel to discard quarkus issue).

**Comment by MarcoMartins86** [comment] 2022-09-29 15:52
On the [elasticsearch-search-source kamelet](https://github.com/apache/camel-kamelets/blob/main/kamelets/elasticsearch-search-source.kamelet.yaml):
````
- to:
            uri: "{{local-es}}:{{clusterName}}"
            parameters:
              operation: "SEARCH"
              indexName: "{{indexName}}"
              hostAddresses: "{{hostAddresses}}"
              enableSSL: "{{enableSSL}}"
              user: "{{?user}}"
              password: "{{?password}}"
````
The `user` and `password` are defined as query parameters if I am understanding correctly but they will never work since as you said they will only work at component level.

**Comment by oscerd** [comment] 2022-09-29 15:55
That's wrong. It should be defined on the bean. Thanks for reporting, now I'm getting the problem.

**Comment by MarcoMartins86** [comment] 2022-09-29 16:05
No problem thanks for coping with this issue with me.

**Comment by oscerd** [comment] 2022-09-29 16:06
I'm sorry I didn't get from the beginning.

**Closed** 2022-09-30 07:47 UTC
